# Generated by Django 4.1.4 on 2023-01-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_sent", models.IntegerField()),
                ("user_to", models.IntegerField()),
                ("message", models.CharField(max_length=1000)),
                ("date_sent", models.DateField()),
                ("message_read", models.BooleanField()),
            ],
        ),
    ]
