# Generated by Django 4.1.4 on 2023-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_totalmessages"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TotalMessages",
        ),
    ]
