# Generated by Django 4.1.4 on 2023-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_password",
            field=models.CharField(default="password", max_length=20),
            preserve_default=False,
        ),
    ]
