# Generated by Django 4.1.4 on 2023-02-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_user_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
